theme: jekyll-theme-minimal
title: Peter Y. Wang
description: PhD in Neuroscience
logo: True
disqus: False
collections:
category:
plugins:
  - jekyll-archives
repository: https://github.com/pwang724/pwang724.github.io

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
